---
sudo: required
dist: trusty
language: bash
install:
  - ./build/install.sh
script:
  - ./build/build.sh
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    skip_join: true
    channels:
      - "irc.freenode.org#virtapi"
